apiVersion: v1
kind: Service
metadata:
  {{ if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{ else }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}-zipkin-server
  {{ end }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
  selector:
    component: zipkin-server
