# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: jkwong/zipkin
  tag: latest
  pullPolicy: Always

service:
  name: zipkin-server
  type: ClusterIP
  port: 9411
  internalPort: 9411

config:
  existingConfigMapName:

spring:
  cloud:
    config:
      enabled: false
      uri:
